"""create data_fields table

Revision ID: 0e3bd8af0cef
Revises: 9794c1c9a964
Create Date: 2024-08-31 16:33:37.347787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3bd8af0cef'
down_revision: Union[str, None] = '9794c1c9a964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_fields',
    sa.Column('interface_id', sa.String(), nullable=False),
    sa.Column('interface_name', sa.String(), nullable=True),
    sa.Column('tr_name', sa.String(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('cumulative_length', sa.Integer(), nullable=True),
    sa.Column('definition', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('interface_id')
    )
    op.create_index(op.f('ix_data_fields_interface_id'), 'data_fields', ['interface_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_fields_interface_id'), table_name='data_fields')
    op.drop_table('data_fields')
    # ### end Alembic commands ###
