"""Initial migration

Revision ID: 10c8f644a643
Revises: b473f133c85f
Create Date: 2024-09-01 16:54:46.184690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c8f644a643'
down_revision: Union[str, None] = 'b473f133c85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derivative_execution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interface_id', sa.String(length=50), nullable=False),
    sa.Column('interface_name', sa.String(length=50), nullable=False),
    sa.Column('tr_name', sa.String(length=50), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=50), nullable=False),
    sa.Column('item_name_en', sa.String(length=50), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('cumulative_length', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_derivative_execution_id'), 'derivative_execution', ['id'], unique=False)
    op.create_table('derivative_execution_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_type', sa.String(length=20), nullable=False),
    sa.Column('tr_code', sa.String(length=20), nullable=False),
    sa.Column('interface_name', sa.String(length=100), nullable=False),
    sa.Column('header_data_type', sa.Enum('HEADER', 'DATA', name='headerdatatype'), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=50), nullable=False),
    sa.Column('item_name_en', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.String(length=5), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_derivative_execution_details_id'), 'derivative_execution_details', ['id'], unique=False)
    op.drop_index('ix_Derivative_execution_id', table_name='Derivative_execution')
    op.drop_table('Derivative_execution')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Derivative_execution',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interface_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('interface_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tr_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('item_name_en', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('decimal_places', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cumulative_length', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('definition', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Derivative_execution_pkey')
    )
    op.create_index('ix_Derivative_execution_id', 'Derivative_execution', ['id'], unique=False)
    op.drop_index(op.f('ix_derivative_execution_details_id'), table_name='derivative_execution_details')
    op.drop_table('derivative_execution_details')
    op.drop_index(op.f('ix_derivative_execution_id'), table_name='derivative_execution')
    op.drop_table('derivative_execution')
    # ### end Alembic commands ###
