"""Initial migration

Revision ID: 63498008c870
Revises: 65131c89fb0a
Create Date: 2024-09-01 16:19:41.005715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63498008c870'
down_revision: Union[str, None] = '65131c89fb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('derivative_trades', sa.Column('interface_id', sa.String(length=10), nullable=False))
    op.add_column('derivative_trades', sa.Column('interface_name', sa.String(length=50), nullable=False))
    op.add_column('derivative_trades', sa.Column('tr_name', sa.String(length=50), nullable=False))
    op.add_column('derivative_trades', sa.Column('sequence_number', sa.Integer(), nullable=False))
    op.add_column('derivative_trades', sa.Column('item_name', sa.String(length=50), nullable=False))
    op.add_column('derivative_trades', sa.Column('item_name_en', sa.String(length=50), nullable=False))
    op.add_column('derivative_trades', sa.Column('decimal_places', sa.Integer(), nullable=False))
    op.add_column('derivative_trades', sa.Column('data_type', sa.String(length=10), nullable=False))
    op.add_column('derivative_trades', sa.Column('length', sa.Integer(), nullable=False))
    op.add_column('derivative_trades', sa.Column('cumulative_length', sa.Integer(), nullable=False))
    op.add_column('derivative_trades', sa.Column('definition', sa.Text(), nullable=True))
    op.add_column('derivative_trades', sa.Column('remarks', sa.Text(), nullable=True))
    op.drop_column('derivative_trades', 'isin_code')
    op.drop_column('derivative_trades', 'message_sequence_number')
    op.drop_column('derivative_trades', 'trading_volume')
    op.drop_column('derivative_trades', 'trading_price')
    op.drop_column('derivative_trades', 'data_category')
    op.drop_column('derivative_trades', 'board_id')
    op.drop_column('derivative_trades', 'trading_time')
    op.drop_column('derivative_trades', 'session_id')
    op.drop_column('derivative_trades', 'trading_date')
    op.drop_column('derivative_trades', 'processing_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('derivative_trades', sa.Column('processing_time', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('derivative_trades', sa.Column('trading_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('derivative_trades', sa.Column('session_id', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.add_column('derivative_trades', sa.Column('trading_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('derivative_trades', sa.Column('board_id', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.add_column('derivative_trades', sa.Column('data_category', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.add_column('derivative_trades', sa.Column('trading_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('derivative_trades', sa.Column('trading_volume', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('derivative_trades', sa.Column('message_sequence_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('derivative_trades', sa.Column('isin_code', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.drop_column('derivative_trades', 'remarks')
    op.drop_column('derivative_trades', 'definition')
    op.drop_column('derivative_trades', 'cumulative_length')
    op.drop_column('derivative_trades', 'length')
    op.drop_column('derivative_trades', 'data_type')
    op.drop_column('derivative_trades', 'decimal_places')
    op.drop_column('derivative_trades', 'item_name_en')
    op.drop_column('derivative_trades', 'item_name')
    op.drop_column('derivative_trades', 'sequence_number')
    op.drop_column('derivative_trades', 'tr_name')
    op.drop_column('derivative_trades', 'interface_name')
    op.drop_column('derivative_trades', 'interface_id')
    # ### end Alembic commands ###
