"""Initial migration

Revision ID: b473f133c85f
Revises: b2570892d489
Create Date: 2024-09-01 16:42:48.422105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b473f133c85f'
down_revision: Union[str, None] = 'b2570892d489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Derivative_execution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interface_id', sa.String(length=50), nullable=False),
    sa.Column('interface_name', sa.String(length=50), nullable=False),
    sa.Column('tr_name', sa.String(length=50), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=50), nullable=False),
    sa.Column('item_name_en', sa.String(length=50), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('cumulative_length', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Derivative_execution_id'), 'Derivative_execution', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Derivative_execution_id'), table_name='Derivative_execution')
    op.drop_table('Derivative_execution')
    # ### end Alembic commands ###
